### ISSUE TITLE
SDL issue list

### ISSUE THREAD

**Issue by Desour** [minetest/irrlicht#137]
This is a list of bugs and other issues we still have with the sdl backend. Please feel free to add more items and/or correct wrong information.

- [x] Mouse spinning issues.
  PR: #123 + https://github.com/minetest/minetest/pull/12636
  (Also at some point (i.e. after dropping all non-SDL backends) we should use relative mouse motion values.)
- [x] Clipboard doesn't work.
  PR: #132 
- [x] Cursor icons API is not implemented.
  PR: #135 
- [x] In inventory, items are always moved as if shift was hold.
  PR: #141 
- [x] Minetest implements some thing platform-dependently, see [minetest/src/client/renderingengine.cpp](https://github.com/minetest/minetest/blob/master/src/client/renderingengine.cpp). (Only found X11 stuff in this file.) On sdl, the stuff doesn't really work. (Also, now that we use our own irrlicht fork, that code can be moved into this repo.)
  The things implemented there include stuff like getting display density or setting window properties.
  PR: #181 + https://github.com/minetest/minetest/pull/13348
- [x] The minetest window window is moved a bit down at each start ~~(about the thickness of the window decoration)~~.
  PR: #142 + https://github.com/minetest/minetest/pull/12861
- ~~[ ] Formspecs look a bit different. (Probably due to missing display size info stuff.)~~
- [x] Compiling with sdl requires modifying sourcecode: https://github.com/minetest/irrlicht/blob/1cf0f3bef04e53c08004cc1106f48fcecca7ff88/include/IrrCompileConfig.h#L47-L48
  Edit: For the record, now it's: `$ cmake -DUSE_SDL2=1 .`
- [x] Pressing the inventory key (`i`) while a formspec is open always closes it, even if a text input field is focused.
  PR:  #146

**Comment by sfan5** [comment]
>  (Also, now that we use our own irrlicht fork, that code can be moved into this repo.)

Getting the display density should definitely be moved, but not sure how easy that is for Android (IIRC we call into Java for this).
I'm not quite sure what we should do about the window icon since it's mostly x11 specific (win32 does it via the manifest, macOS too).

**Comment by Niklp09** [comment]
Typing "i" in a search field closes the formspec

**Comment by ndren** [comment]
@Niklp09 I can reproduce. It is caused by I being bound to inventory, and changing the hotkey fixes it. There needs to be a check if there is some other menu active. I haven't checked the code, but I can confirm that this happens with whichever key the inventory is bound to.

**Comment by Desour** [comment]
> Getting the display density should definitely be moved, but not sure how easy that is for Android (IIRC we call into Java for this). 

Getting exactly the same display density as we do now might be a bit more difficult, as SDL doesn't directly provide the sizes of the whole display.
And `SDL_GetDisplayDPI` gives completely wrong values it seems (tested).
The SDL wiki suggests to use `SDL_GetWindowSize` and `SDL_GL_GetDrawableSize` (or similar) instead. But those need an already existing window, `SDL_GetWindowSize` is not millimeters, but screen coordinates (with non high dpi, this is just pixels if I understand correctly).
So we might end up keeping our platform dependent code. In the worst case, we could still access sdl-internal data if necessary.

> I'm not quite sure what we should do about the window icon since it's mostly x11 specific (win32 does it via the manifest, macOS too).

Apparently windows can also use images:
https://github.com/libsdl-org/SDL/blob/5ed091c12d4edefb366d78217b72cb75b563bfcd/src/video/windows/SDL_windowswindow.c#L645

-----

Btw. I've made a small branch to refactor the code a little (diffs look big, but it's mostly code move), I won't make a PR (at least for now), but you can use it if you want to: https://github.com/Desour/minetest/tree/renderingengine_platform_dependent_code

---------------

Fun fact: If I search for "sdl wiki", the 2nd result is "Sturm der Liebe - Wikipedia".
I guess our new window lib will again have a german name. /s

**Comment by rubenwardy** [comment]
DPI on modern OSes is completely arbitrary, it doesn't necessarily match the real screen size and pixel density. Whilst it starts off as that, Windows scales it using a multiplier in the settings. This allows users to choose how much bigger the text and elements in the GUI appears in different applications

**Comment by ndren** [comment]
Could I have some feedback on the new version of https://github.com/minetest/irrlicht/pull/144? It should be more reliable now.

**Comment by numberZero** [comment]
> The minetest window window is moved a bit down at each start

On my Plasma/X11 it doesn’t; was that fixed in the meanwhile?

> Formspecs look a bit different

Are there any problematic examples? On my 160 DPI screen, formspecs aren’t any worse with SDL than without it.

**Comment by Desour** [comment]
> > The minetest window window is moved a bit down at each start
> 
> On my Plasma/X11 it doesn’t; was that fixed in the meanwhile?

It's not fixed yet. The issue depends on your panel configuration. I.e. if you only have a panel at the bottom and maximize the window, the window is big enough to fill out the entire space above the panel. If you now restart minetest, the window is placed in the middle of the whole screen, aka lower than before.

> > Formspecs look a bit different
> 
> Are there any problematic examples? On my 160 DPI screen, formspecs aren’t any worse with SDL than without it.

I'll try to make screenshots.

**Comment by Desour** [comment]
> > > Formspecs look a bit different
> > 
> > 
> > Are there any problematic examples? On my 160 DPI screen, formspecs aren’t any worse with SDL than without it.
> 
> I'll try to make screenshots.

Ok, can't reproduce. I guess I tested wrongly and accidentally used different window sizes or something. I've crossed out the point now.

**Comment by numberZero** [comment]
The issue is written as:

> The minetest window window is moved a bit down at each start

That is what I can’t reproduce. Minetest doesn’t even save window position so the window can’t move *each* start. It will simply be off-center slightly. Specifically on my system,

* Under Wayland, the entire window is centred on the desktop area.
* Under X11 (including XWayland), the window is centred on the screen under assumption it is not decorated, and then decorated keeping *upper left* corner in place. My WM remedies this a bit moving it upwards if it would intersect the bottom panel but I guess yours doesn’t support that.

**Comment by numberZero** [comment]
> Compiling with sdl requires modifying sourcecode

See #158

**Comment by numberZero** [comment]
> Compiling with sdl requires modifying sourcecode

Fixed with [5a5a7d0](https://github.com/minetest/irrlicht/commit/5a5a7d04b71b576ac9eed1bb58110009f8b46d0b)?

**Comment by numberZero** [comment]
> X11 stuff <...> setting window properties.

SDL takes care of that, mostly. Except of the icon which needs to be supplied explicitly, and also it uses the binary name for `WM_CLASS`.

**Comment by ndren** [comment]
Is there a way to edit source code to enable SDL rather than `cmake -DUSE_SDL2=1 .`? I've had that break when doing partial builds, so I would like to have it compile more consistently.

**Comment by numberZero** [comment]
> Is there a way to edit source code to enable SDL rather than `cmake -DUSE_SDL2=1 .`?

No. There are more things than just compiling `CIrrDeviceSDL` in.

> I've had that break when doing partial builds, so I would like to have it compile more consistently.

Partial rebuilds should work; file a bug if they don’t (but see #182 first, it may very well be your issue).

**Comment by ndren** [comment]
It looks like make sometimes invokes cmake (?) in partial builds which removes the definition of USE_SDL2 (as it is not invoked with the manually provided flag). I can't reproduce reliably though.

Note when I say partial builds, I mean ctrl-C out of a make invocation (e.g. when forgetting to provide `--jobs`).

@numberZero why would replacing `option(USE_SDL2 "Use the SDL2 backend" FALSE)` with `TRUE` not work? It seems to work.

**Comment by numberZero** [comment]
> It looks like make sometimes invokes cmake

Yes it does.

> which removes the definition of USE_SDL2 (as it is not invoked with the manually provided flag).

That shouldn’t happen. `USE_SDL2` is a cache variable, i.e. its value is stored in `CMakeCache.txt` and thus doesn’t need to be provided each time.

> @numberZero why would replacing `option(USE_SDL2 "Use the SDL2 backend" FALSE)` with `TRUE` not work? It seems to work.

That value is only the default, it is not used if the variable is in the cache already.

**Comment by ndren** [comment]
I see, thanks for the explanation. I'll try and reproduce more reliably if it ever happens again.

**Comment by Desour** [comment]
With https://github.com/minetest/minetest/pull/13348 merged, all SDL issues should be fixed now. :tada:
